#!/usr/bin/env python

# usage: bin2h FILE

import sys

fname = sys.argv[1]
f = open(fname, "r")
data = f.read()
f.close()

name = fname[:fname.index(".")]

print "const char array[%d] = {" % len(data),

for i in range(len(data)):
    b = ord(data[i])
    if i & 0x0f == 0:
        sys.stdout.write("\n\t")
    sys.stdout.write("0x%02X" % b)
    if i < len(data) - 1: sys.stdout.write(", ")

print "\n};"
